[features]
seeds = false
skip-lint = false
[programs.devnet]
auction = "6VwSgSesAeqqSw3uXsU8BGMxMAqSzFVQxPPUDUVX8Qw4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../keys/user-Shit.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
